### PR TITLE
add back missing derives

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by stevefan1999-personal** [comment]
Huh, interesting, I never through about the orderings of Unix path and Windows path...but if you don't have PartialOrd then you can't use TypedPathBuf as a key for BTreeMap

**Comment by chipsenkbeil** [comment]
We're in pre 1.0 release, so I'm fine bringing this in. Can always change the behavior later if needed. Thanks for the contribution!

**Comment by stevefan1999-personal** [comment]
> We're in pre 1.0 release, so I'm fine bringing this in. Can always change the behavior later if needed. Thanks for the contribution!

Thanks! Now I can use this with BTreeMap in `no_std` context

**Comment by chipsenkbeil** [comment]
@stevefan1999-personal you'll find this included in the 0.9.1 release :smile:

**Pull request merged**
